### ISSUE TITLE
Loading WASM via static import statemet (question)

### ISSUE THREAD

**Issue by dyedgreen** [KSXGitHub/yaml-wasm#12]
Deno used to (and as far as I know plans to) support importing WASM binaries statically using `import wasm from "/path/to/wasm.wasm"`.

Something similar can be achieved using plain JS as well: The WASM module can be embedded (e.g. as base64) inside a .js file and then downloaded using a static import. While such a scheme slightly increases the file-size of the compiled binary, it has the advantage for Deno users that they don't need to `--allow-net` to use the module and that the module WASM code can be cached by Deno for future executions of the script.

The file size increase is probably not acceptable for browser use, but I feel like for the Deno module this may be an interesting trade-of.

**Comment by KSXGitHub** [comment]
I do this as an experiment rather than a library to be used in production. There's already YAML parsers written in native JavaScript (e.g. [std/encoding/yaml](https://deno.land/std/encoding/yaml.ts) and [js_yaml_port](https://deno.land/x/js_yaml_port)). You should use those.

However, if what you care about is using languages other than JS/TS in Deno. There is [plan](https://github.com/WebAssembly/esm-integration) in place for ES Module integration for WASM module. There is also [assert reference proposal](https://github.com/tc39/proposal-asset-references) that can instruct Deno to store non-JS non-WASM files in cache. I encourage you to support these two proposals for the betterment of all.

**Comment by dyedgreen** [comment]
Thanks for the very rapid reply! 😃
